nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    # defaults:
    #     origin_regex: false
    #     allow_origin: []
    #     allow_methods: []
    #     allow_headers: []
    #     expose_headers: []
    #     allow_credentials: false
    #     max_age: 0
    #     hosts: []
    paths:
        '^/api': ~
